# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='id',
        ),
        migrations.AlterField(
            model_name='sport',
            name='idno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
