# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-03 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180326_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_level',
            field=models.IntegerField(default=0),
        ),
    ]
