# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180325_2034'),
        ('main', '0006_auto_20180326_0442'),
    ]

    operations = [
    ]
