# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-03 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customuser_admin_level'),
        ('main', '0007_merge_20180326_1343'),
    ]

    operations = [
    ]
