# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20180403_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcontrols',
            name='dd_no',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
