# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_billcontrols_dd_no'),
        ('main', '0008_auto_20180404_1607'),
    ]

    operations = [
    ]
