# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_enteredplayer_all_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acco_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('common_room', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_room', to='main.Accomodation')),
                ('s_room', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_room', to='main.Accomodation')),
                ('tt_room', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tt_room', to='main.Accomodation')),
            ],
        ),
    ]
