# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20180404_1835'),
        ('main', '0009_enteredplayer_all_done'),
    ]

    operations = [
    ]
