# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-21 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_controls_user_firewallz_user_recnacc_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
