# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-17 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_controls_user_firewallz_user_recnacc_user'),
        ('main', '0011_merge_20180404_1934'),
    ]

    operations = [
    ]
