# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-07 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='docs2',
            field=smartfields.fields.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='orderid1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='orderid2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='orderid3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pay1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pay2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pay3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pcramt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='regplayer',
            name='email_id',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='regplayer',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regplayer',
            name='unbilled_amt',
            field=models.IntegerField(default=1100),
        ),
    ]
