# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regplayer',
            name='email_id',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='regplayer',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
