# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-07 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180907_1833'),
        ('main', '0016_auto_20180725_1117'),
    ]

    operations = [
    ]
