# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180325_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
