# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180325_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='fifty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='fivehundred',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='hundred',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='twohundred',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='twothousand',
            field=models.IntegerField(null=True),
        ),
    ]
