# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180325_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='enteredplayer',
            name='controls_displayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enteredplayer',
            name='recnacc_displayed',
            field=models.BooleanField(default=False),
        ),
    ]
