# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180404_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='enteredplayer',
            name='all_done',
            field=models.BooleanField(default=False),
        ),
    ]
