# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-19 12:07
from __future__ import unicode_literals

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_pcradmin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='docs',
            field=smartfields.fields.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
