# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-20 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180717_0955'),
        ('main', '0014_auto_20180719_1207'),
    ]

    operations = [
    ]
