# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-03 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180725_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='regplayer',
            name='uid',
            field=models.CharField(default=' ', max_length=10000000000000000),
        ),
    ]
