# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-03 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_regplayer_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regplayer',
            name='unbilled_amt',
            field=models.IntegerField(default=1100),
        ),
    ]
