# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-11 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_merge_20180907_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='regplayer',
            name='blood_grp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='regplayer',
            name='notes',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
    ]
