# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-07 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_merge_20180720_1031'),
        ('main', '0017_merge_20180907_1845'),
        ('main', '0017_auto_20180831_1416'),
    ]

    operations = [
    ]
