# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-12 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_merge_20180907_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='regplayer',
            name='blood_grp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='regplayer',
            name='notes',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
