# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-15 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_regplayer_uid'),
        ('main', '0019_auto_20180913_0720'),
    ]

    operations = [
    ]
