# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-17 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_regplayer_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='fine',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='mf',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='regplayer',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='regplayer',
            name='bitsian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regplayer',
            name='fine',
            field=models.FloatField(default=0),
        ),
    ]
