# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-18 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180917_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regplayer',
            name='mobile_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
