# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-15 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20180915_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='fine',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='regplayer',
            name='fine',
            field=models.FloatField(default=0),
        ),
    ]
