# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-18 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20180918_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='ten',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='money',
            name='twenty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
