# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-15 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20180915_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='regplayer',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
