# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-16 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_regplayer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='regplayer',
            name='bitsian',
            field=models.BooleanField(default=False),
        ),
    ]
