# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-26 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20180918_2308'),
        ('main', '0026_regplayer_bitsian'),
    ]

    operations = [
    ]
